version: '3.8'

services:
  app:
    image: php:8.1-apache
    container_name: kiu_php_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: bash -c "composer install && apache2-foreground"
    depends_on:
      - composer

  composer:
    image: composer:latest
    container_name: kiu_composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html